// this file is automatically generated by xrm.py from the uh svn repo
// generated 2020-04-17

module bcm_init #(
	parameter DATA_BUS_WIDTH = 8,
	parameter ADDRESS_BUS_DEPTH = 14
) (
	input clock_slow,
	input clock_fast,
	input reset,
	output reg [ADDRESS_BUS_DEPTH-1:0] write_address = 0,
	output reg write_enable = 0,
	output reg [DATA_BUS_WIDTH-1:0] data_out = 0,
	output reg done = 0
);
	reg [7:0] values_array [4:0][48:0];
	reg [2:0] index_array [333:0];
	reg [2:0] values_array_counter_1 = 0;
	reg [5:0] values_array_counter_2 = 0;
	reg [8:0] index_array_counter = 0;
	reg [3:0] initializing_stage = 0;
	always @(posedge clock_slow) begin
		if (reset) begin
			initializing_stage <= 0;
			values_array_counter_1 <= 0;
			values_array_counter_2 <= 0;
			index_array_counter <= 0;
		end else begin
			values_array_counter_2 <= values_array_counter_2 + 1'b1;
			if (initializing_stage==0) begin
				case (values_array_counter_2)
					49: begin values_array_counter_1 <= values_array_counter_1 + 1'b1; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: values_array[values_array_counter_1][values_array_counter_2] <= 8'h00;
				endcase
			end else if (initializing_stage==1) begin
				case (values_array_counter_2)
					0: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					1: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					3: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					4: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					6: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					7: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					9: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					10: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					12: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					13: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					15: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					16: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					18: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					49: begin values_array_counter_1 <= values_array_counter_1 + 1'b1; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: values_array[values_array_counter_1][values_array_counter_2] <= 8'h00;
				endcase
			end else if (initializing_stage==2) begin
				case (values_array_counter_2)
					3: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					4: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					6: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					7: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					9: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					10: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					12: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					13: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					15: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					16: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					18: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					19: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					21: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					22: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					24: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					26: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					27: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					29: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					30: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					32: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					33: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					35: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					36: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					38: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					39: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					41: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					42: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					44: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					45: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					47: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					49: begin values_array_counter_1 <= values_array_counter_1 + 1'b1; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: values_array[values_array_counter_1][values_array_counter_2] <= 8'h00;
				endcase
			end else if (initializing_stage==3) begin
				case (values_array_counter_2)
					0: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					1: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					3: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					4: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					6: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					7: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					9: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					10: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					12: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					13: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					15: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					16: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					18: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					19: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					21: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					23: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					49: begin values_array_counter_1 <= values_array_counter_1 + 1'b1; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: values_array[values_array_counter_1][values_array_counter_2] <= 8'h00;
				endcase
			end else if (initializing_stage==4) begin
				case (values_array_counter_2)
					0: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					1: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					3: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					4: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					6: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					7: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					9: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					10: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					12: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					13: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					15: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					16: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					18: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					19: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					21: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					22: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					24: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					26: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					27: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					29: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					30: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					32: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					33: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					35: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					36: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					38: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					39: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					41: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					42: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					44: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					45: values_array[values_array_counter_1][values_array_counter_2] <= 8'h0f;
					47: values_array[values_array_counter_1][values_array_counter_2] <= 8'hf0;
					49: begin values_array_counter_1 <= values_array_counter_1 + 1'b1; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: values_array[values_array_counter_1][values_array_counter_2] <= 8'h00;
				endcase
			end else if (initializing_stage==5) begin
				index_array_counter <= index_array_counter + 1'b1;
				case (index_array_counter)
					0: index_array[index_array_counter] <= 3'h4;
					1: index_array[index_array_counter] <= 3'h4;
					2: index_array[index_array_counter] <= 3'h4;
					3: index_array[index_array_counter] <= 3'h4;
					4: index_array[index_array_counter] <= 3'h4;
					5: index_array[index_array_counter] <= 3'h4;
					6: index_array[index_array_counter] <= 3'h4;
					7: index_array[index_array_counter] <= 3'h4;
					8: index_array[index_array_counter] <= 3'h4;
					9: index_array[index_array_counter] <= 3'h4;
					10: index_array[index_array_counter] <= 3'h4;
					11: index_array[index_array_counter] <= 3'h4;
					12: index_array[index_array_counter] <= 3'h1;
					13: index_array[index_array_counter] <= 3'h2;
					14: index_array[index_array_counter] <= 3'h4;
					15: index_array[index_array_counter] <= 3'h4;
					16: index_array[index_array_counter] <= 3'h4;
					17: index_array[index_array_counter] <= 3'h4;
					18: index_array[index_array_counter] <= 3'h4;
					19: index_array[index_array_counter] <= 3'h4;
					20: index_array[index_array_counter] <= 3'h4;
					21: index_array[index_array_counter] <= 3'h4;
					22: index_array[index_array_counter] <= 3'h4;
					23: index_array[index_array_counter] <= 3'h4;
					24: index_array[index_array_counter] <= 3'h4;
					25: index_array[index_array_counter] <= 3'h3;
					334: begin index_array_counter <= 0; values_array_counter_2 <= 0; initializing_stage <= initializing_stage + 1'b1; end
					default: index_array[index_array_counter] <= 3'h0;
				endcase
			end else if (initializing_stage==6) begin
				if (initialized) begin
					initializing_stage <= initializing_stage + 1'b1;
				end
			end
		end
	end
	reg [ADDRESS_BUS_DEPTH-1:0] counter = 0;
	reg initialized = 0;
	reg [5:0] values_array_counter_3 = 0;
	reg [8:0] index_array_counter_2 = 0;
	always @(posedge clock_fast) begin
		if (reset) begin
			counter <= 0;
			write_enable <= 0;
			write_address <= 0;
			data_out <= 0;
			initialized <= 0;
			values_array_counter_3 <= 0;
			index_array_counter_2 <= 0;
			done <= 0;
		end else begin
			if (!initialized) begin
				if (initializing_stage==6) begin
					values_array_counter_3 <= values_array_counter_3 + 1'b1;
					write_enable <= 1;
					write_address <= counter;
					if (values_array_counter_3==48) begin
						values_array_counter_3 <= 0;
						if (index_array_counter_2==333) begin
							index_array_counter_2 <= 0;
							initialized <= 1;
						end else begin
							index_array_counter_2 <= index_array_counter_2 + 1'b1;
						end
					end else begin
						data_out <= values_array[index_array[index_array_counter_2]][values_array_counter_3];
					end
					counter <= counter + 1'b1;
				end
			end else begin
				write_enable <= 0;
				write_address <= 0;
				data_out <= 0;
				done <= 1;
			end
		end
	end
endmodule


